[platformio]
default_envs = desenvolvimento

[base_para_projeto]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.30-2/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
; lib_deps = libs/
build_type = release
upload_speed = 921600
;upload_speed = 2000000
monitor_speed = 115200

build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
	-Os
	-Wl,--gc-sections

board_build.filesystem = littlefs
board_build.partitions = partitions.csv
board_build.arduino.memory_type = dio_opi 
board_upload.flash_size = 16MB
board_upload.before_reset = usb_reset

[env:desenvolvimento]
extends = base_para_projeto
build_src_filter = +<camera.cpp> -<teste.cpp>

[env:teste]
extends = base_para_projeto
build_src_filter = +<teste.cpp> -<camera.cpp>

[env:final]
extends = base_para_projeto
build_src_filter = -<*.cpp>